const execute = require('./connection');
const express = require('express');
const router = express.Router();

router.post("/documento", async(req,res)=>{

    const{sucursal,coddoc,correlativo} = req.body;

    let qry = `
        SELECT 
            DOCUMENTOS_1.FECHA, 
            DOCUMENTOS_1.CODDOC, 
            DOCUMENTOS_1.CORRELATIVO, 
            DOCUMENTOS_1.DOC_NIT AS NIT, 
            DOCUMENTOS_1.DOC_NOMCLIE AS NOMCLIE, 
            DOCUMENTOS_1.DOC_DIRCLIE AS DIRCLIE, 
            DOCUMENTOS_1.TOTALPRECIO, 
            EMPLEADOS.NOMEMPLEADO AS EMPLEADO, 
            ISNULL(DOCUMENTOS_1.FPAGO_EFECTIVO, 0) AS FPAGO_EFECTIVO, 
            ISNULL(DOCUMENTOS_1.FPAGO_TARJETA, 0) AS FPAGO_TARJETA, 
            ISNULL(DOCUMENTOS_1.FPAGO_DEPOSITO, 0) AS FPAGO_DEPOSITO, 
            ISNULL(DOCUMENTOS_1.FPAGO_CHEQUE, 0) AS FPAGO_CHEQUE, 
            ISNULL(DOCUMENTOS_1.FPAGO_DESCRIPCION, '') AS FPAGO_DESCRIPCION, 
            DOCUMENTOS_FACTURAS_ABONADAS.CODDOC_FAC, 
            DOCUMENTOS_FACTURAS_ABONADAS.CORRELATIVO_FAC, 
            DOCUMENTOS.FECHA AS FECHA_FAC, 
            DOCUMENTOS_FACTURAS_ABONADAS.ABONO, 
            CLIENTES.TELEFONOCLIENTE AS TELCLIE, 
            DOCUMENTOS.FEL_SERIE, 
            DOCUMENTOS.FEL_NUMERO
        FROM  DOCUMENTOS RIGHT OUTER JOIN
            DOCUMENTOS_FACTURAS_ABONADAS ON DOCUMENTOS.CORRELATIVO = DOCUMENTOS_FACTURAS_ABONADAS.CORRELATIVO_FAC AND DOCUMENTOS.CODDOC = DOCUMENTOS_FACTURAS_ABONADAS.CODDOC_FAC AND
            DOCUMENTOS.EMPNIT = DOCUMENTOS_FACTURAS_ABONADAS.EMPNIT RIGHT OUTER JOIN
            DOCUMENTOS AS DOCUMENTOS_1 LEFT OUTER JOIN
            CLIENTES ON DOCUMENTOS_1.EMPNIT = CLIENTES.EMPNIT AND DOCUMENTOS_1.CODCLIENTE = CLIENTES.CODCLIENTE LEFT OUTER JOIN
            EMPLEADOS ON DOCUMENTOS_1.EMPNIT = EMPLEADOS.EMPNIT AND DOCUMENTOS_1.CODVEN = EMPLEADOS.CODEMPLEADO ON 
            DOCUMENTOS_FACTURAS_ABONADAS.CORRELATIVO = DOCUMENTOS_1.CORRELATIVO AND DOCUMENTOS_FACTURAS_ABONADAS.CODDOC = DOCUMENTOS_1.CODDOC AND 
            DOCUMENTOS_FACTURAS_ABONADAS.EMPNIT = DOCUMENTOS_1.EMPNIT
        WHERE 
            (DOCUMENTOS_1.CODDOC = '${coddoc}') AND 
            (DOCUMENTOS_1.CORRELATIVO = ${correlativo}) AND 
            (DOCUMENTOS_1.EMPNIT = '${sucursal}');    
            `
    


     execute.Query(res,qry);

     
});


module.exports = router;

